version: '3'

services:

  # workspace for using artisan commands in your local
  workspace:
    build: workspace
    container_name: Symfony_test_workspace
    volumes:
      - ../Symfony/myproject:/var/www/html/
    command: bash
    environment:
      - STAGE=docker
    depends_on:
      - mysql
      - cache

  # php + webserver
  apache:
    build: apache
    container_name: Symfony_test_apache
    volumes:
      - ../Symfony/myproject:/var/www/html/
    ports:
      - 8010:80
    environment:
      - STAGE=docker

  # DB in your local
  mysql:
    image: mysql:5.7
    container_name: Symfony_test_mysql
    ports:
      - '3310:3306'
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - Symfony_test_mysql:/var/lib/mysql

  # cache server
  cache:
    image: memcached
    container_name: Symfony_test_cache

volumes:
    Symfony_test_mysql:
        driver: "local"
